# Generated by Django 2.0.1 on 2018-03-09 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document_field_list', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentfieldlist',
            name='created_by',
        ),
    ]
