# Generated by Django 2.0.1 on 2018-03-09 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_field_list', '0002_remove_documentfieldlist_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentfieldlist',
            name='name',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Field Name'),
        ),
    ]
