# Generated by Django 2.0.1 on 2018-03-09 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document_field_list', '0003_auto_20180309_1042'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentfieldlist',
            old_name='name',
            new_name='field_name',
        ),
    ]
