# Generated by Django 2.0.1 on 2018-03-09 04:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import herofiles.apps.commons.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('document_type', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('alive', herofiles.apps.commons.fields.LiveField(db_index=True, default=True)),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Name')),
                ('condition', models.IntegerField(choices=[(0, 'Text'), (1, 'Number'), (2, 'Date')], db_index=True, verbose_name='Condition')),
                ('key', models.IntegerField(choices=[(0, 'Optional'), (1, 'Required')], db_index=True, verbose_name='Key')),
                ('created_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='documentfield_created_user', to=settings.AUTH_USER_MODEL, verbose_name='Created User')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentField', to='document_type.DocumentType')),
                ('updated_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='documentfield_updated_user', to=settings.AUTH_USER_MODEL, verbose_name='Updated User')),
            ],
            options={
                'verbose_name': 'Document Field',
            },
        ),
    ]
