# Generated by Django 2.0.1 on 2018-03-09 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('document_field', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentfield',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field', to='document_type.DocumentType'),
        ),
    ]
