# Generated by Django 2.0.1 on 2018-03-12 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document_field', '0004_auto_20180309_1044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentfield',
            name='alive',
        ),
        migrations.RemoveField(
            model_name='documentfield',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='documentfield',
            name='created_user',
        ),
        migrations.RemoveField(
            model_name='documentfield',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='documentfield',
            name='updated_user',
        ),
    ]
