# Generated by Django 2.0.1 on 2018-03-09 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document_type', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documenttype',
            name='created_by',
        ),
    ]
